### ISSUE TITLE
KerbalFoundries Support

### ISSUE THREAD

**Issue by docmop** [Real-Gecko/KSP-BonVoyage#2]
As the KerbalFoundries wheel mod is now a thing again. It would be great if it could be supported by this mod.

Links:
[Kerbal Foundries Forum Post](http://forum.kerbalspaceprogram.com/index.php?/topic/155056-122-kerbal-foundries-continued-tracks-wheels-and-gear-02-05-17/)
[KSPWheel Repository](https://github.com/shadowmage45/KSPWheel)

**Comment by Real-Gecko** [comment]
Coming coming coming:
![monster truck maddness](http://imgur.com/VB4zrUL.png)
