### ISSUE TITLE
Landing gears is not wheels?

### ISSUE THREAD

**Issue by byaka** [Real-Gecko/KSP-BonVoyage#5]
![image](https://cloud.githubusercontent.com/assets/1580811/23878149/becb9958-0856-11e7-9e58-27fdfe73b95d.png)
As i understand, this happened because [this](https://github.com/Real-Gecko/KSP-BonVoyage/blob/master/BonVoyage/BonVoyageModule.cs#L128) iter only motorized wheels.

**Comment by Real-Gecko** [comment]
Yep, only ModuleWheels with ModuleWheelMotor are taken in account.

**Comment by byaka** [comment]
Can u pls fix it?

**Comment by Real-Gecko** [comment]
Nothing to fix IMO. Just add two more wheels ;)

**Comment by byaka** [comment]
It strange limitation, because mod allow wheels with disabled motors, but dissalow wheels without motors. Also this limitation lower variants for tiny rovers (small moto-wheel is 50kg, small wheel is 15kg).

**Comment by Real-Gecko** [comment]
It's not limitation, it's possibility. Each possibility in KSP mod is a pain in the ass.
Check [this procedure](https://github.com/Real-Gecko/KSP-BonVoyage/blob/master/BonVoyage/BonVoyageModule.cs#L109) to see what I'm talking about.

**Comment by byaka** [comment]
Ok, thx for answer..

**Comment by Real-Gecko** [comment]
You'll get this with next release.

**Comment by byaka** [comment]
Glad to hear, thx!

**Comment by byaka** [comment]
Thx for new release, my kerbals happy now!

**Comment by Real-Gecko** [comment]
You're welcome.

**Comment by Real-Gecko** [comment]
By the way, I lied, you'll still need at least 4 wheels, but landing gear are treated as usable wheels too now :D

**Comment by byaka** [comment]
That's fine for me :)
Not tested yet myself, is new version dissalow rovers, that not has motorized wheels? It will be cheating..

**Comment by Real-Gecko** [comment]
Well, you need at least four wheels to be touching the ground (landing gear is accounted) and at least two of your wheels must be powered. The design from screenshot above will work now, until you have enough power and your wheels are intact.
By the way, take a look at [Kerbal Foundries -- Continued](http://forum.kerbalspaceprogram.com/index.php?/topic/155056-122-kerbal-foundries-continued-tracks-wheels-and-gear-03-05-17/). It has pretty cool variety of wheels and tracks. Theese are supported now too.
I dunno why am I doing all this, all this power calculations and wheels check and pathfinding. Sometimes I think that no one cares :D :D :D
