### ISSUE TITLE
Rover loading issue

### ISSUE THREAD

**Issue by Snakedog49** [Real-Gecko/KSP-BonVoyage#9]
Whenever I load in my rover from doing a drive. If it is halfway through the ground. It explodes. If it is fully clipped through the ground then it falls to sea level and explodes. But if the whole rover is above ground it just falls down. And while I know explosions are cool and all its killing my crew members and a lot of money is being invested in rescue missions that end up exploding because of this. It makes me afraid to open my rovers after sending them to a destination. This has been happening in the most recent version of the game. Please fix!

**Comment by jarosm** [comment]
Issue moved to the new repo: https://github.com/jarosm/KSP-BonVoyage/issues/1
